package dev.lochistory.cli;

import dev.lochistory.analysis.AnalysisProgress;
import dev.lochistory.analysis.GitCommandException;
import dev.lochistory.analysis.LocHistoryAnalyzer;
import dev.lochistory.model.HistoryResult;
import dev.lochistory.model.LocSnapshot;
import dev.lochistory.model.FileMetrics;

import java.io.PrintStream;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Files;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public final class LocHistoryCli {
    private LocHistoryCli() {}

    public static void main(String[] args) {
        int code = run(args, System.out, System.err);
        if (code != 0) System.exit(code);
    }

    static int run(String[] args, PrintStream out, PrintStream err) {
        try {
            Options options = Options.parse(args);
            if (options.help) {
                usage(out);
                return 0;
            }
            LocHistoryAnalyzer analyzer = new LocHistoryAnalyzer(options.repository);
            if (options.listBranches) {
                analyzer.branches(AnalysisProgress.NONE).forEach(out::println);
                return 0;
            }
            String branch = options.branch;
            if (branch == null || branch.isBlank()) branch = analyzer.currentBranch(AnalysisProgress.NONE);
            if (branch.isBlank()) throw new IllegalArgumentException("Detached HEAD: specify --branch <name>");
            HistoryResult result = analyzer.analyze(branch, options.commits, options.sampleEvery,
                    options.quiet ? AnalysisProgress.NONE : new StderrProgress(err));
            String report = options.format.equals("markdown")
                    ? renderMarkdown(result, options.compare == null ? null :
                        analyzer.snapshot(options.compare, AnalysisProgress.NONE))
                    : renderTsv(result);
            if (options.check != null) {
                String existing = Files.exists(options.check) ? Files.readString(options.check) : "";
                if (!existing.equals(report)) {
                    err.println("LOC report is stale: " + options.check);
                    return 3;
                }
            } else if (options.output != null) {
                Path parent = options.output.toAbsolutePath().getParent();
                if (parent != null) Files.createDirectories(parent);
                Files.writeString(options.output, report, StandardCharsets.UTF_8);
            } else {
                out.print(report);
            }
            return 0;
        } catch (IllegalArgumentException e) {
            err.println("error: " + e.getMessage());
            usage(err);
            return 2;
        } catch (GitCommandException e) {
            err.println("git error: " + e.getMessage());
            return 1;
        } catch (IOException e) {
            err.println("I/O error: " + e.getMessage());
            return 1;
        }
    }

    private static String renderTsv(HistoryResult result) {
        java.io.ByteArrayOutputStream bytes = new java.io.ByteArrayOutputStream();
        PrintStream out = new PrintStream(bytes, true, StandardCharsets.UTF_8);
        out.println("branch\tcommit\ttimestamp\tpath\tkind\trloc\tloc\trloc_percent");
        for (LocSnapshot snapshot : result.snapshots()) {
            List<String> folders = collectFolders(snapshot);
            emit(out, result.branch(), snapshot, ".", "folder",
                    snapshot.linesFor("", false, true), snapshot.linesFor("", false, false));
            folders.forEach(path -> emit(out, result.branch(), snapshot, path, "folder",
                    snapshot.linesFor(path, false, true), snapshot.linesFor(path, false, false)));
            snapshot.metricsByFile().entrySet().stream().sorted(MapEntryComparator.INSTANCE)
                    .forEach(entry -> emit(out, result.branch(), snapshot, entry.getKey(), "file",
                            entry.getValue().rloc(), entry.getValue().loc()));
        }
        return bytes.toString(StandardCharsets.UTF_8);
    }

    private static String renderMarkdown(HistoryResult result, LocSnapshot base) {
        StringBuilder text = new StringBuilder("# Lines of code history\n\n");
        text.append("Generated by LOC History Visualizer for `").append(md(result.branch())).append("`. ")
                .append("Counts are physical lines in Git-tracked text files.\n\n");
        if (result.snapshots().isEmpty()) return text.append("No commits found.\n").toString();
        LocSnapshot latest = result.snapshots().get(result.snapshots().size() - 1);
        int total = latest.linesFor("", false);
        text.append("## Current total\n\n**").append(String.format("%,d", total)).append(" LOC** at `")
                .append(latest.commit().shortHash()).append("`");
        if (base != null) {
            int old = base.linesFor("", false);
            text.append(" (delta from `").append(base.commit().shortHash()).append("`: **")
                    .append(signed(total - old)).append("**)");
        }
        text.append("\n\n## History\n\n| Commit | Date | LOC | Change |\n|---|---:|---:|---:|\n");
        Integer previous = null;
        for (LocSnapshot snapshot : result.snapshots()) {
            int count = snapshot.linesFor("", false);
            text.append("| `").append(snapshot.commit().shortHash()).append("` | ")
                    .append(snapshot.commit().time().toString(), 0, 10).append(" | ")
                    .append(String.format("%,d", count)).append(" | ")
                    .append(previous == null ? "—" : signed(count - previous)).append(" |\n");
            previous = count;
        }
        text.append("\n## Latest folders\n\n| Folder | LOC | Share |").append(base == null ? "" : " Delta |").append("\n")
                .append(base == null ? "|---|---:|---:|\n" : "|---|---:|---:|---:|\n");
        topFolders(latest).forEach(folder -> {
            int count = latest.linesFor(folder, false);
            text.append("| `").append(md(folder)).append("` | ").append(String.format("%,d", count))
                    .append(" | ").append(String.format("%.1f%%", count * 100.0 / Math.max(1, total))).append(" |");
            if (base != null) text.append(' ').append(signed(count - base.linesFor(folder, false))).append(" |");
            text.append('\n');
        });
        return text.toString();
    }

    private static List<String> topFolders(LocSnapshot snapshot) {
        return collectFolders(snapshot).stream().filter(path -> !path.contains("/"))
                .sorted(Comparator.comparingInt((String path) -> snapshot.linesFor(path, false)).reversed())
                .limit(20).toList();
    }

    private static String signed(int number) {
        return (number > 0 ? "+" : "") + String.format("%,d", number);
    }

    private static String md(String value) {
        return value.replace("|", "\\|").replace("`", "\\`");
    }

    private static List<String> collectFolders(LocSnapshot snapshot) {
        java.util.Set<String> folders = new java.util.TreeSet<>();
        for (String file : snapshot.metricsByFile().keySet()) {
            int slash = file.lastIndexOf('/');
            while (slash >= 0) {
                folders.add(file.substring(0, slash));
                slash = file.lastIndexOf('/', slash - 1);
            }
        }
        return new ArrayList<>(folders);
    }

    private static void emit(PrintStream out, String branch, LocSnapshot snapshot,
                             String path, String kind, int rloc, int loc) {
        out.printf("%s\t%s\t%s\t%s\t%s\t%d\t%d\t%.2f%n", clean(branch), snapshot.commit().hash(),
                DateTimeFormatter.ISO_INSTANT.format(snapshot.commit().time()), clean(path), kind, rloc, loc,
                loc == 0 ? 0 : rloc * 100.0 / loc);
    }

    private static String clean(String value) {
        return value.replace('\t', ' ').replace('\n', ' ').replace('\r', ' ');
    }

    private static void usage(PrintStream stream) {
        stream.println("Usage: loc-history [--repo PATH] [--branch NAME] [--commits N] [--sample-every N]");
        stream.println("                   [--format tsv|markdown] [--compare REF] [--output FILE|--check FILE] [--quiet]");
        stream.println("       loc-history [--repo PATH] --list-branches");
        stream.println("Writes tab-separated folder and file LOC records to stdout.");
    }

    private static final class StderrProgress implements AnalysisProgress {
        private final PrintStream err;
        private StderrProgress(PrintStream err) { this.err = err; }
        @Override public void update(double fraction, String message) { err.print("\r" + message + "   "); }
    }

    private enum MapEntryComparator implements Comparator<java.util.Map.Entry<String, FileMetrics>> {
        INSTANCE;
        @Override public int compare(java.util.Map.Entry<String, FileMetrics> left,
                                     java.util.Map.Entry<String, FileMetrics> right) {
            return left.getKey().compareTo(right.getKey());
        }
    }

    private static final class Options {
        private Path repository = Path.of(".").toAbsolutePath().normalize();
        private String branch;
        private int commits = 60;
        private int sampleEvery = 1;
        private boolean listBranches;
        private boolean quiet;
        private boolean help;
        private String format = "tsv";
        private String compare;
        private Path output;
        private Path check;

        private static Options parse(String[] args) {
            Options value = new Options();
            for (int i = 0; i < args.length; i++) {
                switch (args[i]) {
                    case "--repo" -> value.repository = Path.of(requireValue(args, ++i, "--repo")).toAbsolutePath().normalize();
                    case "--branch" -> value.branch = requireValue(args, ++i, "--branch");
                    case "--commits" -> value.commits = positive(requireValue(args, ++i, "--commits"), "--commits");
                    case "--sample-every" -> value.sampleEvery = positive(requireValue(args, ++i, "--sample-every"), "--sample-every");
                    case "--list-branches" -> value.listBranches = true;
                    case "--quiet" -> value.quiet = true;
                    case "--format" -> value.format = requireValue(args, ++i, "--format");
                    case "--compare" -> value.compare = requireValue(args, ++i, "--compare");
                    case "--output" -> value.output = Path.of(requireValue(args, ++i, "--output"));
                    case "--check" -> value.check = Path.of(requireValue(args, ++i, "--check"));
                    case "-h", "--help" -> value.help = true;
                    default -> throw new IllegalArgumentException("Unknown option: " + args[i]);
                }
            }
            if (!value.format.equals("tsv") && !value.format.equals("markdown"))
                throw new IllegalArgumentException("--format must be tsv or markdown");
            if (value.output != null && value.check != null)
                throw new IllegalArgumentException("Use only one of --output or --check");
            return value;
        }

        private static String requireValue(String[] args, int index, String option) {
            if (index >= args.length) throw new IllegalArgumentException(option + " needs a value");
            return args[index];
        }

        private static int positive(String raw, String option) {
            try {
                int value = Integer.parseInt(raw);
                if (value < 1) throw new NumberFormatException();
                return value;
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException(option + " must be a positive integer");
            }
        }
    }
}
